server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: marcket-cliente
          uri: http://localhost:8081
          predicates:
            - Path=/cliente/**

        - id: marcket-producto
          uri: http://localhost:8081
          predicates:
            - Path=/producto/**

        - id: marcket-admin
          uri: http://localhost:8081
          predicates:
            - Path=/admin/**

        - id: inventario
          uri: http://localhost:8085
          predicates:
            - Path=/inventario/**

        - id: venta
          uri: http://localhost:8088
          predicates:
            - Path=/venta/**
# Springdoc config para centralizar documentaci贸n
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Gesti贸n de administradores
        url: http://localhost:8081/v3/api-docs
      - name: Gesti贸n de Inventario
        url: http://localhost:8085/v3/api-docs
      - name: Gesti贸n de Venta
        url: http://localhost:8088/v3/api-docs

#http://localhost:8080/swagger-ui.html